### ISSUE TITLE
It's impossible to download binary data using send-request

### ISSUE THREAD

**Issue by hiiamboris** [rebolek/red-tools#6]
https://github.com/rebolek/red-tools/blob/1daeee54f4bac33849b43ffcb8525bef28c9fad7/http-tools.red#L672

**Comment by rebolek** [comment]
@hiiamboris Thanks for the report! However this version is no longer supported, it moved to https://gitlab.com/rebolek/castr/ . Please, check `send-request` from the CASTR suite, instead of brute force string conversion it now checks MIME type (and codepage for text) and tries to convert data to proper Red type. Let me know if you still have problems with the latest version.

I'm going to update the readme to point people to the right version.

**Comment by hiiamboris** [comment]
from what I see in the code it's no gonna work either
if you download a file from a server it can be "text/plain" or "application/pdf" or anything really, you just need to save it as is, without any conversion (linefeed or charset or whatever)
send-request provides no option for that
as a temporary workaround I just made it not do any conversion under /raw option, but it's a crutch
rather, this should be in the design of send-request

**Comment by rebolek** [comment]
Ok, I need to take a look at the MIME system and check it. It probably should register some common codecs like PDF and probably providing `/binary` refinement for dealing with situations where MIME doesn't work would help too.
